version: '3.8'
services:
  database:
    image: postgres:17
    environment:
      POSTGRES_DB: ${DB_NAME:-users_db}
      POSTGRES_USER: ${DB_USER:-admin}
      POSTGRES_PASSWORD: ${DB_PASS:-admin}
    volumes:
      - "./backend/core/init.sql:/docker-entrypoint-initdb.d/init.sql:ro"
      - "./data/postgres/postgres_data:/var/lib/postgresql/data"
    ports:
      - "5432:5432"

  messagebase:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER:-admin}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASS:-admin}
    volumes:
      - "./data/mongo/mongo_data:/data/db"
    ports:
          - "27017:27017"
  app:
    build: .
    volumes:
      - ./logs:/app/backend/logs
    ports:
      - "80:80"

volumes:
  postgres_data:
  mongo_data: