version: '3.8'
services:
  database:
    image: postgres:17
    volumes:
      - "./init.sql:/docker-entrypoint-initdb.d/init.sql:ro"
      - "./data/postgres_data:/var/lib/postgresql/data"
    environment:
      POSTGRES_DB: users_db
      POSTGRES_USER: ${DB_USER:-admin}
      POSTGRES_PASSWORD: ${DB_PASS:-admin}
    ports:
      - "5432:5432"


  backend:
    build: backend/.
    environment:
      - JWT_SECRET=${JWT_SECRET:-supersecretkey}
      - DB_USER=${DB_USER:-admin}
      - DB_PASS=${DB_PASS:-admin}
      - DB_USERS_NAME=users_db
      - DB_MESSAGES_NAME=messages_db
  frontend:
    build: frontend/.
    ports:
      - "80:80"

volumes:
  postgres_data: